# Generated by Django 3.2 on 2021-04-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residencia', models.IntegerField(choices=[(1, 'casa'), (2, 'apartamento')], verbose_name='Tipo da residencia')),
                ('n_pavimentos', models.IntegerField(blank=True, verbose_name='Número de apartamentos')),
                ('n_pessoas', models.IntegerField(verbose_name='Número de residentes')),
                ('tarifa_esgoto', models.FloatField(verbose_name='Porcentagem da tarifa de esgoto')),
                ('consumo_mensal', models.FloatField(verbose_name='Consumo mensal de água')),
                ('area_cobertura', models.FloatField(verbose_name='Área de cobertura')),
                ('area_pisos', models.FloatField(verbose_name='Área de pisos')),
                ('area_irrigacao', models.FloatField(verbose_name='Área de irrigação')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
            },
        ),
        migrations.CreateModel(
            name='DemandasDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do consumo')),
                ('frequencia_mensal', models.IntegerField(verbose_name='Frequencia mensal de uso')),
                ('indicador', models.FloatField(blank=True, verbose_name='Indicador de uso final')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='simulacao.simulacao', verbose_name='Simulacao pertencente')),
            ],
            options={
                'verbose_name': 'Demanda de Água',
                'verbose_name_plural': 'Demandas de Água',
                'ordering': ['nome'],
            },
        ),
    ]
