# Generated by Django 3.2 on 2021-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_auto_20210422_1512'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demandasdeagua',
            constraint=models.UniqueConstraint(fields=('simulacao', 'nome'), name='simulação única'),
        ),
    ]
