# Generated by Django 3.2 on 2021-09-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0005_auto_20210430_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertasDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da oferta')),
                ('frequencia_mensal', models.IntegerField(verbose_name='Frequencia mensal de uso')),
                ('indicador', models.FloatField(blank=True, verbose_name='Indicador de uso final')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ofertas', to='simulacao.simulacao', verbose_name='Simulacao pertencente')),
            ],
        ),
    ]
