# Generated by Django 3.2 on 2021-10-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0006_ofertasdeagua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasdeagua',
            name='simulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='simulacao.simulacao', verbose_name='Simulacao pertencente'),
        ),
    ]
