# Generated by Django 3.2 on 2022-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0007_alter_ofertasdeagua_simulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandasdeagua',
            name='unidade',
            field=models.CharField(choices=[('Litros/m²/dia', 'Litros/m²/dia'), ('Litros/pessoa/dia', 'Litros/pessoa/dia')], default='Litros/pessoa/dia', max_length=17, verbose_name='Unidade de medida do indicador de uso final'),
        ),
    ]
