# Generated by Django 3.2.13 on 2022-05-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0010_simulacao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO ', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='DF', max_length=24, verbose_name='Estado (UF)'),
        ),
    ]
