# Generated by Django 3.2 on 2022-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0011_alter_simulacao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='cidade',
            field=models.CharField(default='BRASILIA', max_length=50, verbose_name='Cidade'),
        ),
    ]
