# Generated by Django 3.2.13 on 2022-06-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0013_alter_simulacao_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsosDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do consumo')),
                ('frequencia_mensal', models.IntegerField(verbose_name='Frequencia mensal de uso')),
                ('indicador', models.FloatField(blank=True, verbose_name='Indicador de uso final')),
                ('unidade', models.CharField(choices=[('Litros/m²/dia', 'Litros/m²/dia'), ('Litros/pessoa/dia', 'Litros/pessoa/dia')], default='Litros/pessoa/dia', max_length=17, verbose_name='Unidade de medida do indicador de uso final')),
                ('demanda', models.BooleanField(blank=True, verbose_name='Utilizado como demanda')),
                ('oferta', models.BooleanField(blank=True, verbose_name='Utilizado como oferta')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='simulacao.simulacao', verbose_name='Simulacao pertencente')),
            ],
            options={
                'verbose_name': 'Demanda de Água',
                'verbose_name_plural': 'Demandas de Água',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='ofertasdeagua',
            name='simulacao',
        ),
        migrations.DeleteModel(
            name='DemandasDeAgua',
        ),
        migrations.DeleteModel(
            name='OfertasDeAgua',
        ),
        migrations.AddConstraint(
            model_name='usosdeagua',
            constraint=models.UniqueConstraint(fields=('simulacao', 'nome'), name='simulação única'),
        ),
    ]
