# Generated by Django 3.2.13 on 2022-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0015_auto_20220606_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='abr',
            field=models.BooleanField(default=False, verbose_name='Estiagem em abril'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='ago',
            field=models.BooleanField(default=True, verbose_name='Estiagem em agosto'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='dez',
            field=models.BooleanField(default=False, verbose_name='Estiagem em dezembro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fev',
            field=models.BooleanField(default=False, verbose_name='Estiagem em fevereiro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='jan',
            field=models.BooleanField(default=False, verbose_name='Estiagem em janeiro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='jul',
            field=models.BooleanField(default=True, verbose_name='Estiagem em julho'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='jun',
            field=models.BooleanField(default=True, verbose_name='Estiagem em junho'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='mai',
            field=models.BooleanField(default=True, verbose_name='Estiagem em maio'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='mar',
            field=models.BooleanField(default=False, verbose_name='Estiagem em março'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='nov',
            field=models.BooleanField(default=False, verbose_name='Estiagem em novembro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='out',
            field=models.BooleanField(default=False, verbose_name='Estiagem em outubro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='set',
            field=models.BooleanField(default=True, verbose_name='Estiagem em setembro'),
        ),
    ]
