# Generated by Django 3.2 on 2021-04-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_min', models.IntegerField(verbose_name='Área minima')),
                ('area_max', models.IntegerField(verbose_name='Área maxima')),
            ],
            options={
                'verbose_name': 'Area de coleta',
                'verbose_name_plural': 'Areas de coleta',
                'ordering': ['area_min'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='IndicePluviometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(0, 'Janeiro'), (1, 'Fevereiro'), (2, 'Março'), (3, 'Abril'), (4, 'Maio'), (5, 'Junho'), (6, 'Julho'), (7, 'Agosto'), (8, 'Setembro'), (9, 'Outubro'), (10, 'Novembro'), (11, 'Dezembro')], verbose_name='Mês')),
                ('media_pluviometrica', models.IntegerField(verbose_name='Média pluviométrica em mm')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='base_de_dados.cidade', verbose_name='Cidade pertencente')),
            ],
            options={
                'verbose_name': 'Índice pluviométrico',
                'verbose_name_plural': 'Índices pluviométricos',
                'ordering': ['ano'],
            },
        ),
        migrations.AddConstraint(
            model_name='indicepluviometrico',
            constraint=models.UniqueConstraint(fields=('cidade', 'mes', 'ano'), name='índice pluviométrico único'),
        ),
    ]
