# Generated by Django 3.2 on 2021-05-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_dagua', models.IntegerField(verbose_name="filtro d'água")),
                ('sifao_ladrao', models.IntegerField(verbose_name='Sifão ladrão')),
                ('freio_dagua', models.IntegerField(verbose_name="Freio d'água")),
                ('area_de_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='base_de_dados.areadecoleta', verbose_name='Area de coleta relacionada')),
            ],
            options={
                'verbose_name': 'Equipamento de dimensionamento',
                'verbose_name_plural': 'Equipamentos de dimensionamento',
                'ordering': ['area_de_coleta'],
            },
        ),
    ]
