# Generated by Django 3.2 on 2021-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0002_equipamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavimentos_min', models.IntegerField(verbose_name='Mínimo de pavimentos')),
                ('pavimentos_max', models.IntegerField(verbose_name='Máximo de pavimentos')),
                ('potencia', models.FloatField(verbose_name='Cavalos de potência')),
                ('consumo', models.FloatField(verbose_name='Consumo de enegia em Kilowatts/hora')),
                ('tarifa', models.FloatField(verbose_name='Tarifa em Kilowatts/hora')),
                ('succao', models.IntegerField(verbose_name='Sucção da bomba')),
                ('recalque', models.IntegerField(verbose_name='Recalque da bomba')),
                ('preco', models.FloatField(verbose_name='Preço de compra da bomba')),
                ('horas_uso', models.IntegerField(verbose_name='Total horas de uso por ano')),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipamentos',
            options={'ordering': ['area_de_coleta'], 'verbose_name': 'Equipamento para dimensionamento', 'verbose_name_plural': 'Equipamentos para dimensionamento'},
        ),
    ]
