# Generated by Django 3.2 on 2021-05-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0004_auto_20210526_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifadeagua',
            name='max',
            field=models.IntegerField(null=True, verbose_name='Faixa de consumo máxima'),
        ),
    ]
