# Generated by Django 3.2 on 2021-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0005_alter_tarifadeagua_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='custo_implementacao',
            field=models.FloatField(default=0, verbose_name='custo de implementação em Dólares'),
        ),
    ]
