# Generated by Django 3.2 on 2021-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0006_equipamentos_custo_implementacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=0, verbose_name='Mínimo')),
                ('max', models.IntegerField(default=500, verbose_name='Máximo')),
                ('volume', models.IntegerField(default=500, verbose_name='Vólume')),
                ('valor', models.FloatField(default=53.05, verbose_name='Valor em dólares')),
            ],
            options={
                'verbose_name': "Caixa D'água",
                'verbose_name_plural': "Caixas D'água",
                'ordering': ['min'],
            },
        ),
    ]
