# Generated by Django 3.2 on 2021-05-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0007_caixadagua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixadagua',
            name='volume',
            field=models.IntegerField(default=500, verbose_name='Volume'),
        ),
    ]
