# Generated by Django 3.2 on 2021-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0009_capacidadedetratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadedetratamento',
            name='custo_operacional',
            field=models.FloatField(default=0.4, verbose_name='Custo Operacional ($)'),
        ),
    ]
