# Generated by Django 3.2 on 2022-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0010_capacidadedetratamento_custo_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombadeagua',
            name='consumo',
            field=models.FloatField(verbose_name='Consumo de enegia em Kilowatts-hora'),
        ),
        migrations.AlterField(
            model_name='bombadeagua',
            name='tarifa',
            field=models.FloatField(verbose_name='Tarifa em Kilowatts-hora'),
        ),
        migrations.AlterField(
            model_name='caixadagua',
            name='valor',
            field=models.FloatField(default=200.0, verbose_name='Valor em reais'),
        ),
        migrations.AlterField(
            model_name='capacidadedetratamento',
            name='custo_operacional',
            field=models.FloatField(default=1.5, verbose_name='Custo Operacional (R$)'),
        ),
        migrations.AlterField(
            model_name='capacidadedetratamento',
            name='valor',
            field=models.FloatField(default=25000, verbose_name='Valor em reais'),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='custo_implementacao',
            field=models.FloatField(default=0, verbose_name='custo de implementação em Reais'),
        ),
    ]
