# Generated by Django 3.2.13 on 2022-06-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_dados', '0016_alter_cidade_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifadeagua',
            name='max',
        ),
        migrations.RemoveField(
            model_name='tarifadeagua',
            name='min',
        ),
    ]
